language: python
python:
  - "3.3"
env:
  - PJ=webservice
    DJANGO_VERSION=1.5.2
    DJANGO_SETTINGS_MODULE=webservice.test_settings
    DBA_SQL_DJANGO_ENGINE='django.db.backends.mysql'
    DBA_SQL_DB_NAME='webservice_test_2'
    DBA_SQL_ADMIN_USER=travis
    DBA_SQL_ADMIN_PASSWORD=''
    DBA_SQL_HOST='127.0.0.1'
    DBA_SQL_PORT='3306'

services:
  - mysql

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r $PJ/requirements.txt  --use-mirrors
  - pip install -r $PJ/requirements-dev.txt --use-mirrors
  - cd dependents/easy-thumbnails && python setup.py install && cd -
  - cd dependents/django-tagging && python setup.py install && cd -
  - cd dependents/django-tagging-autocomplete && python setup.py install && cd -

before_script:
  - mysql -e 'create database webservice_test_2;'
  - cd $PJ && python manage.py syncdb --noinput && cd -
  - cd $PJ && python manage.py migrate && cd -

after_script:
  - mysql -e 'drop database webservice_test_2'

script:
  - cd $PJ
  - coverage run manage.py test warehouse taxonomy
  - cd -

after_success:
  - coveralls
